### PR TITLE
Upgrade the exporter to support OpenSearch 2.12.0

### PR DESCRIPTION
**Pull request by cesium147**
## Description

Describe your PR and add links to relevant issues.

---

- [x] All my commits include DCO.<br>_DCO stands for **Developer Certificate of Origin** and it is your declaration that your contribution is correctly attributed and licensed. Please read more about how to attach DCO to your commits [here](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) (spoiler alert: in most cases it is as simple as using `-s` option when doing `git commit`).<br>Please be aware that commits without DCO will cause failure of PR CI workflow and can not be merged._

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
I need to look at it, it might be related to java version used in CI. Currently, it is JDK 14
https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/blob/main/.github/workflows/CI.yml#L15
but we might want to upgrade to 17 or 21.

**Comment by amirkkn** [comment]
Hi @lukas-vlcek,
we use this exporter in all of our infrastructure and due to a lot of bugs in 2.11 we must upgrade ASAP. Do you any ETA for the release for 2.12.0? Thanks

**Review by lukas-vlcek — APPROVED** [review]
LGTM

**Comment by lukas-vlcek** [comment]
@cesium147 I had to do one merge from `main` during review and now the PR passes but can not be merged... I am not sure why...

**Comment by lukas-vlcek** [comment]
@cesium147 What happened is that I had to upgrade to gradle 8.5 and at the same time I upgraded CI to JDK 17. See https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/pull/253/commits
Now, our PR somehow does not want to be merged (and rebased) because I did one merge commit...

Do you think you can open a new PR and we will close this one? I am not really sure what is going on. I should not have been using GitHub web UI to manipulate commits... I am sorry.

Other than that the upgrade is looking good.

**Comment by lukas-vlcek** [comment]
Great, thanks @cesium147 !

**Comment by grechaw** [comment]
Thank you all for your work on this.  We love upgrading and the exporter is a critical piece of it.

**Comment by lukas-vlcek** [comment]
FYI: Plugin version `2.12.0.0` has been released. The following is a forum announcement: https://forum.opensearch.org/t/prometheus-exporter-plugin-2-12-0-0-released/18105

**Pull request merged**
